# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozm9kqgs4XrB2owA66B_uus6B_ndI2sW
"""

import pandas as pd

data={
    "Ism":["Sojida","Zohida","Dildora","Oygul","Nozima"],
    "Familiya":["Abdulvohidova","Akhmadova","Obidova","Mamaroziqova","Zafarjonova"],
    "Manzili": ["Margilon","Rishton","Toshloq","Dangara","Beshariq"],
    "Yoshi": [19,19,19,18,18],
    "Jinsi":["ayol","ayol","ayol","ayol","ayol"]
}
baza=pd.DataFrame(data)
print(baza)

filtr=baza[baza["Yoshi"]>18]
print(filtr)

baza["Yoshi"]+=7
print(baza)

filtr=baza[baza["Yoshi"]<18]
print(filtr)

baza.to_excel("Roʼyxat.xlsx")

